version: '3.8'

services:
  steam-share-app:
    build: .
    container_name: steam-share-app
    ports:
      - "1515:1515"
    environment:
      - PORT=${PORT:-1515}
      - USER_1_API_KEY=${USER_1_API_KEY}
      - USER_1_STEAM_ID=${USER_1_STEAM_ID}
      - USER_1_NAME=${USER_1_NAME}
      - USER_2_API_KEY=${USER_2_API_KEY}
      - USER_2_STEAM_ID=${USER_2_STEAM_ID}
      - USER_2_NAME=${USER_2_NAME}
      - USER_3_API_KEY=${USER_3_API_KEY:-}
      - USER_3_STEAM_ID=${USER_3_STEAM_ID:-}
      - USER_3_NAME=${USER_3_NAME:-}
    restart: unless-stopped
